spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  redis:
    host: localhost
    port: 6379

#server log setting
logging:
  file:
    name: /Users/jojaeyeong/Desktop/tomcat/test_server.log
  level:
    '*': info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
    file: '%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p}
      ${PID:- } --- [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
    level: '%5p'

#tomcat access log setting
server:
  port: 8080
  tomcat:
    accesslog:
      directory: /Users/jojaeyeong/Desktop/tomcat
      enabled: true
      file-date-format: .yyyy-MM-dd
      max-days: 14
      pattern: '%h %l %u %t "%r" %s %b %D'
      prefix: test_access
      rotate: true
      suffix: .log


file:
  dir: /Users/jojaeyeong/Desktop/upload/